### ISSUE TITLE
Crashes when setting brightness (DEV branch)

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee-shepherd-converters#148]
For my GLEDOPTO RGB LED controller I switched to the dev branch. The strip now works (thanks again) but zigbee2mqtt crashed when I try to set a light's brightness. Turning it on and off works.

This is the output when running in debug mode:

```
zigbee2mqtt:debug 2018-11-28 21:01:20 Received MQTT message on 'zigbee/0x000b57fffed602e5/set' with data '{"brightness":119.85}'
/opt/zigbee2mqtt_dev/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:65
                if (value.includes('%')) {
                          ^

TypeError: value.includes is not a function
    at Object.convert (/opt/zigbee2mqtt_dev/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:65:27)
    at Object.keys.forEach (/opt/zigbee2mqtt_dev/lib/extension/devicePublish.js:119:41)
    at Array.forEach (<anonymous>)
    at DevicePublish.onMQTTMessage (/opt/zigbee2mqtt_dev/lib/extension/devicePublish.js:111:27)
    at results.extensions.filter.map (/opt/zigbee2mqtt_dev/lib/controller.js:121:27)
    at Array.map (<anonymous>)
    at Controller.onMQTTMessage (/opt/zigbee2mqtt_dev/lib/controller.js:121:14)
    at MQTT.onMessage (/opt/zigbee2mqtt_dev/lib/mqtt.js:81:18)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)

```

**Comment by andreasbrett** [comment]
I'm on commit 1666e133119ecfb6b1a584d8cdf307c8ddef3eef

**Comment by JLFN** [comment]
@Koenkk 
I copied zigbee-shepherd-converters-dev it still dont work.

**Comment by Koenkk** [comment]
@JLFN can you provide the log?

**Comment by JLFN** [comment]
> @JLFN can you provide the log?

I disabled the device information and it now works for me.
