### ISSUE TITLE
Philips Hue dimmer switch error

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-shepherd-converters#329]
i have here a error with the dimmer RWL021

uncaught exception: Invalid cluster id: manuSpecificPhilips.

**Comment by Koenkk** [comment]
@kirovilya is the zcl-id and zcl-packet on my latest version?

**Comment by arteck** [comment]
ahh .. i updated the project selfmate.. and i forgot the dependency

sry

**Comment by arteck** [comment]
new problem

 at new FuncPayload (/opt/iobroker/node_modules/zigbee-shepherd/node_modules/zcl-packet/lib/functional.js:41:15)
    at /opt/iobroker/node_modules/zigbee-shepherd/node_modules/zcl-packet/lib/zcl.js:33:22
    at Dissolve.<anonymous> (/opt/iobroker/node_modules/zigbee-shepherd/node_modules/zcl-packet/lib/zcl.js:121:9)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Dissolve.emit (events.js:211:7)
    at Dissolve.<anonymous> (/opt/iobroker/node_modules/dissolve-chunks/index.js:73:29)
    at emitNone (events.js:106:13)
    at Dissolve.emit (events.js:208:7)
    at emitReadable_ (/opt/iobroker/node_modules/dissolve/node_modules/readable-stream/lib/_stream_readable.js:456:10)

**Comment by Koenkk** [comment]
Is zigbee-shepherd also at the latest version? Can you post more logging?

**Comment by arteck** [comment]
so new turn... del zigbee2mqtt project and new istall
https://github.com/Koenkk/zigbee2mqtt/issues/1237

**Comment by arteck** [comment]
is better
