### ISSUE TITLE
TypeError: Cannot read property 'attrs' of undefined on fromZigbee.js:1295

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee-shepherd-converters#408]
Dear Koenkk.
Thank you very much for your excellent work. I am trying to integrate Meazon meters into zb2mqtt.
Just hit a crash on fromzigbee.js.

Log dump:
2019-04-17T18:26:46.202Z zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: {"groupid":0,"clusterid":1794,"srcaddr":862,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":44,"securityuse":0,"timestamp":6696296,"transseqnumber":0,"len":43,"data":{"0":24,"1":15,"2":1,"3":0,"4":0,"5":0,"6":37,"7":13,"8":24,"9":0,"10":0,"11":0,"12":0,"13":1,"14":0,"15":0,"16":37,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":7,"24":0,"25":0,"26":226,"27":125,"28":19,"29":78,"30":92,"31":23,"32":0,"33":0,"34":42,"35":23,"36":0,"37":0,"38":0,"39":2,"40":0,"41":24,"42":0},"zclMsg":{"frameCntl":{"frameType":0,"manufSpec":0,"direction":1,"disDefaultRsp":1},"manufCode":0,"seqNum":15,"cmdId":"readRsp","payload":[{"attrId":0,"status":0,"dataType":37,"attrData":[0,6157]},{"attrId":1,"status":0,"dataType":37,"attrData":[0,0]},{"attrId":7,"status":0,"dataType":226,"attrData":1548620669},{"attrId":23,"status":0,"dataType":42,"attrData":23},{"attrId":512,"status":0,"dataType":24,"attrData":0}]}}
  zigbee2mqtt:debug 4/17/2019, 8:26:46 PM Received zigbee message of type 'readRsp' with data '{"cid":"seMetering","data":{"currentSummDelivered":[0,6157],"currentSummReceived":[0,0],"readingSnapshotTime":1548620669,"inletTempreature":23,"status":0}}' of device '101.301.001649' (0x00124b0002cc8261) of endpoint 10
/zigbee2mqtt-1.3.1/node_modules/zigbee-shepherd-converters/converters/fromZigbee.js:1295
                const attrs = endpoint.clusters['seMetering'].attrs;
                                                              ^
TypeError: Cannot read property 'attrs' of undefined
    at Object.convert (/zigbee2mqtt-1.3.1/node_modules/zigbee-shepherd-converters/converters/fromZigbee.js:1295:63)
    at converters.forEach (/zigbee2mqtt-1.3.1/lib/extension/deviceReceive.js:192:41)
    at Array.forEach (<anonymous>)
    at DeviceReceive.onZigbeeMessage (/zigbee2mqtt-1.3.1/lib/extension/deviceReceive.js:190:20)
    at extensions.filter.forEach (/zigbee2mqtt-1.3.1/lib/controller.js:145:31)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeMessage (/zigbee2mqtt-1.3.1/lib/controller.js:145:14)
    at Zigbee.onMessage (/zigbee2mqtt-1.3.1/lib/zigbee.js:224:18)
    at ZShepherd.emit (events.js:182:13)
    at ZShepherd.<anonymous> (/zigbee2mqtt-1.3.1/node_modules/zigbee-shepherd/lib/shepherd.js:192:14)

new device being defined in devices.js:
    // Meazon Plug
    {
        zigbeeModel: ['101.301.001649'],
        model: 'Plug',
        vendor: 'Meazon',
        description: 'Plug',
        supports: 'on/off, power, energy measurement and temperature',
        fromZigbee: [fz.state, fz.ignore_onoff_change, fz.generic_power, fz.ignore_metering_change,
        ],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 10);
            const onOff = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 5, repChange: 0};
            const LineFrequency = {
                direction: 0, attrId: 8192, dataType: 'int16', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const ActivePower = {
                direction: 0, attrId: 8193, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const Voltage = {
                direction: 0, attrId: 8196, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const Current = {
                direction: 0, attrId: 8199, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const ReactivePower = {
                direction: 0, attrId: 8202, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const ApparentPower = {
                direction: 0, attrId: 8205, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const PowerFactor = {
                direction: 0, attrId: 8208, dataType: 'singlePrec', minRepIntval: 0, maxRepIntval: 3, repChange: 0,
            };
            const InletTemperature = {
                direction: 0, attrId: 8211, dataType: 'int16', minRepIntval: 0, maxRepIntval: 1000, repChange: 0,
            };
//            const electricalCfg = [LineFrequency, ActivePower, Voltage, Current, ReactivePower, ApparentPower, PowerFactor, InletTemperature,];
            const electricalCfg = [LineFrequency,];
            const actions = [
                (cb) => device.foundation('genOnOff', 'configReport', [onOff], foundationCfg, cb),
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('seMetering', 'configReport', electricalCfg, {manufSpec: 1, manufCode: 4406}, cb),
                (cb) => device.bind('seMetering', coordinator, cb),
            ];

            execute(device, actions, callback);
        },
    },

Let me know if more info is required. Thank you.
 Carlos

**Comment by Koenkk** [comment]
Can you change https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L1306 to

```js
                const attrs = endpoint.clusters['seMetering'] ? endpoint.clusters['seMetering'].attrs : null;
                let energyFactor = 1;
                if (attrs && attrs.multiplier && attrs.divisor) {
                    energyFactor = attrs.multiplier / attrs.divisor;
                }
```

**Comment by ccorderod** [comment]
Koen, no need to change the code. It was a bug in the code I wrotten in the converter for the meazon meter. I do have by now 12 of those things running. As soon as I double check everything is fine I will PR both devices.js and fromZigbee.js codes.
Thank you.
 C.
