### ISSUE TITLE
TypeError: Cannot read property 'disFeedbackRsp' of undefined

### ISSUE THREAD

**Issue by vstoms** [Koenkk/zigbee-shepherd-converters#494]
Running on an Synology NAS with Docker, have today just two philips hue bulbs for testing. This setup is working fine without _-v $(pwd)/data/zigbee-shepherd-converters:/app/node_modules/zigbee-shepherd-converters_ mount. But if I add this and switching on the bulb and everything stops.

I do also have _-v $(pwd)/data/lib/extension/homeassistant.js:/app/lib/extension/homeassistant.js_ added

6/27/2019, 5:38:42 PM - info: Logging to directory: '/app/data/log/2019-06-27.17-38-42'
6/27/2019, 5:38:43 PM - info: Starting zigbee2mqtt version 1.4.0 (commit #unknown)
6/27/2019, 5:38:43 PM - info: Starting zigbee-shepherd
6/27/2019, 5:38:44 PM - info: zigbee-shepherd started
6/27/2019, 5:38:44 PM - info: Coordinator firmware version: '20190608'
6/27/2019, 5:38:44 PM - info: Currently 2 devices are joined:
6/27/2019, 5:38:44 PM - info: 0x0017880102b5ede4 (0x0017880102b5ede4): 8718696449691 - Philips Hue White Single bulb B22 (Router)
6/27/2019, 5:38:44 PM - info: 0x0017880102cf24cc (0x0017880102cf24cc): 8718696449691 - Philips Hue White Single bulb B22 (Router)
6/27/2019, 5:38:44 PM - info: Zigbee: disabling joining new devices.
6/27/2019, 5:38:44 PM - info: Connecting to MQTT server at mqtt://10.0.0.38
6/27/2019, 5:38:45 PM - info: zigbee-shepherd ready
6/27/2019, 5:38:45 PM - info: Connected to MQTT server
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'zigbee2mqtt/0x0017880102b5ede4', payload '{"state":"ON","linkquality":44,"brightness":254}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'zigbee2mqtt/0x0017880102cf24cc', payload '{"state":"ON","linkquality":36,"brightness":254}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'homeassistant/light/0x0017880102b5ede4/light/config', payload '{"brightness":true,"schema":"json","command_topic":"zigbee2mqtt/0x0017880102b5ede4/set","state_topic":"zigbee2mqtt/0x0017880102b5ede4","name":"0x0017880102b5ede4_light","unique_id":"0x0017880102b5ede4_light_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x0017880102b5ede4","name":"0x0017880102b5ede4","sw_version":"Zigbee2mqtt 1.4.0","model":"Hue White Single bulb B22 (8718696449691)","manufacturer":"Philips"},"availability_topic":"zigbee2mqtt/bridge/state"}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'homeassistant/sensor/0x0017880102b5ede4/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x0017880102b5ede4","json_attributes_topic":"zigbee2mqtt/0x0017880102b5ede4","name":"0x0017880102b5ede4_linkquality","unique_id":"0x0017880102b5ede4_linkquality_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x0017880102b5ede4","name":"0x0017880102b5ede4","sw_version":"Zigbee2mqtt 1.4.0","model":"Hue White Single bulb B22 (8718696449691)","manufacturer":"Philips"},"availability_topic":"zigbee2mqtt/bridge/state"}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'homeassistant/light/0x0017880102cf24cc/light/config', payload '{"brightness":true,"schema":"json","command_topic":"zigbee2mqtt/0x0017880102cf24cc/set","state_topic":"zigbee2mqtt/0x0017880102cf24cc","name":"0x0017880102cf24cc_light","unique_id":"0x0017880102cf24cc_light_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x0017880102cf24cc","name":"0x0017880102cf24cc","sw_version":"Zigbee2mqtt 1.4.0","model":"Hue White Single bulb B22 (8718696449691)","manufacturer":"Philips"},"availability_topic":"zigbee2mqtt/bridge/state"}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'homeassistant/sensor/0x0017880102cf24cc/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x0017880102cf24cc","json_attributes_topic":"zigbee2mqtt/0x0017880102cf24cc","name":"0x0017880102cf24cc_linkquality","unique_id":"0x0017880102cf24cc_linkquality_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x0017880102cf24cc","name":"0x0017880102cf24cc","sw_version":"Zigbee2mqtt 1.4.0","model":"Hue White Single bulb B22 (8718696449691)","manufacturer":"Philips"},"availability_topic":"zigbee2mqtt/bridge/state"}'
6/27/2019, 5:38:45 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.4.0","commit":"unknown","coordinator":20190608,"log_level":"info","permit_join":false}'

### **And now the docker crashing:**

2019-06-27 17:28:31,stdout,    at MqttClient.emit (events.js:182:13)

2019-06-27 17:28:31,stdout,    at MQTT.onMessage (/app/lib/mqtt.js:81:18)

2019-06-27 17:28:31,stdout,    at Controller.onMQTTMessage (/app/lib/controller.js:152:14)

2019-06-27 17:28:31,stdout,    at Array.map (<anonymous>)

2019-06-27 17:28:31,stdout,    at results.extensions.filter.map (/app/lib/controller.js:152:27)

2019-06-27 17:28:31,stdout,    at DevicePublish.onMQTTMessage (/app/lib/extension/devicePublish.js:157:14)

2019-06-27 17:28:31,stdout,    at Array.forEach (<anonymous>)

2019-06-27 17:28:31,stdout,    at keys.forEach (/app/lib/extension/devicePublish.js:171:48)

2019-06-27 17:28:31,stdout,    at Object.convert (/app/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:222:57)

2019-06-27 17:28:31,stdout,    at Object.convert (/app/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:70:34)

2019-06-27 17:28:31,stdout,TypeError: Cannot read property 'disFeedbackRsp' of undefined

2019-06-27 17:28:31,stdout,

2019-06-27 17:28:31,stdout,                                 ^

2019-06-27 17:28:31,stdout," cfg: options.disFeedbackRsp ? cfg.defaultdisFeedbackRsp : cfg.default,
"
2019-06-27 17:28:31,stdout,/app/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:70

### **My DB:**

{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e1f78a","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1561656087,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280],"clusters":{"ssIasZone":{"dir":{"value":2},"cmdRsps":{"enrollReq":{"exec":"_exec_"},"statusChangeNotification":{"exec":"_exec_"}}}}}},"_id":"LrqsuUBUI5h7KRjY"}
{"id":2,"type":"Router","ieeeAddr":"0x0017880102b5ede4","nwkAddr":39642,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","epList":[11,242],"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"swBuildId":"1.46.13_r26312","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"manufacturerName":"Philips","modelId":"LWB010","dateCode":"20181115","powerSource":1,"swBuildId":"1.46.13_r26312"}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"16384":254,"currentLevel":254,"remainingTime":0}},"genOta":{"dir":{"value":2},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{"genGreenPowerProxy":{"dir":{"value":3},"attrs":{}}}}},"dateCode":"20181115","_id":"PWWwSojoFAd0lADZ"}
{"id":3,"type":"Router","ieeeAddr":"0x0017880102cf24cc","nwkAddr":47015,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","epList":[11,242],"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"swBuildId":"1.46.13_r26312","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"manufacturerName":"Philips","modelId":"LWB010","dateCode":"20181115","powerSource":1,"swBuildId":"1.46.13_r26312"}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"16384":254,"currentLevel":254,"remainingTime":0}},"genOta":{"dir":{"value":2},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{"genGreenPowerProxy":{"dir":{"value":3},"attrs":{}}}}},"dateCode":"20181115","_id":"yAiLaGJ52v5yKnpK"}
{"$$indexCreated":{"fieldName":"id","unique":true,"sparse":false}}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e1f78a","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6],"status":"online","joinTime":1561656467,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}}},"_id":"LrqsuUBUI5h7KRjY"}
{"id":2,"type":"Router","ieeeAddr":"0x0017880102b5ede4","nwkAddr":39642,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","epList":[11,242],"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"swBuildId":"1.46.13_r26312","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"manufacturerName":"Philips","modelId":"LWB010","dateCode":"20181115","powerSource":1,"swBuildId":"1.46.13_r26312"}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"16384":254,"currentLevel":254,"remainingTime":0}},"genOta":{"dir":{"value":2},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{"genGreenPowerProxy":{"dir":{"value":3},"attrs":{}}}}},"dateCode":"20181115","_id":"PWWwSojoFAd0lADZ"}
{"id":3,"type":"Router","ieeeAddr":"0x0017880102cf24cc","nwkAddr":47015,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LWB010","epList":[11,242],"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"swBuildId":"1.46.13_r26312","status":"offline","joinTime":null,"endpoints":{"11":{"profId":49246,"epId":11,"devId":256,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"manufacturerName":"Philips","modelId":"LWB010","dateCode":"20181115","powerSource":1,"swBuildId":"1.46.13_r26312"}},"genIdentify":{"dir":{"value":1},"attrs":{"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"16384":254,"currentLevel":254,"remainingTime":0}},"genOta":{"dir":{"value":2},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{"genGreenPowerProxy":{"dir":{"value":3},"attrs":{}}}}},"dateCode":"20181115","_id":"yAiLaGJ52v5yKnpK"}
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e1f78a","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1561656467,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280],"clusters":{"ssIasZone":{"dir":{"value":2},"cmdRsps":{"enrollReq":{"exec":"_exec_"},"statusChangeNotification":{"exec":"_exec_"}}}}}},"_id":"LrqsuUBUI5h7KRjY"}

**Comment by vstoms** [comment]
Using latest-dev and now working, closing this thread.
